#!/bin/sh
SHA=$(git rev-parse HEAD)
DATE=$(date +%Y-%m-%d)

cat > dashboard/version.js <<EOF
// -- Interface version ------------------------------------------------------
// This file is managed automatically by git commit hook.
window.INTERFACE_VERSION_DATE = "$DATE";
window.INTERFACE_VERSION_SHA  = "$SHA";
EOF
